### ISSUE TITLE
[solved]Musescore 2.0.2/2.0.3 craches after installing the plugins 

### ISSUE THREAD

**Issue by dgy18787** [rousselmanu/msc_plugins#1]
I've tried musescore 2.0.2 and 2.0.3 under windows 10 with the chord identifier, and i found that it ran well for the first time after i enable the plugins, but once I closed musescore and open again, musescore will crashes if I don't delete the musesocre directory under c:/users/***/appdata. Is there and solution on that?

**Comment by rousselmanu** [comment]
It seems to be a problem with an import command. Could you try to uncomment "import QtQuick 2.3" in the beginning of the plugin file ? 
What if you run it through the "plugin creator" ? Does it throw an error ?

**Comment by dgy18787** [comment]
uncomment "import QtQuick 2.3"  then delete the musescore directory in appdata seems to solve the problem :-D but i don't know how it works...

**Comment by rousselmanu** [comment]
Fixed in v1.2.2
