### ISSUE TITLE
No note colouring option

### ISSUE THREAD

**Issue by asyschikov** [rousselmanu/msc_plugins#6]
Great plugin, works like a charm, but it would be great is it was possible not to color notes.

**Comment by rousselmanu** [comment]
Thank you for your feedback!
Sorry for the delay. I didn't look at this plugin for a looong time and didn't see your question. 
If you open the "qml" file you can change the lines that color the notes:
Go to lines 38 to 41 ([here](https://github.com/rousselmanu/msc_plugins/blob/89980a933c663a82f58764e23c8bad8eabc4848c/chordIdentifier.qml#L38-L41)) and change #A00000, #803030, etc. to #000000 to paint it black ;-)
